#pragma once

#define LED_PIN 14
#define BUCKBOOST_SCL_PIN 2
#define BUCKBOOST_SDA_PIN 3
#define LVL_SENS_TEST_SIG_PIN 18
#define LVL_SENS_READ_PIN 27

#define BUCKBOOST_SLAVE_ADDRESS 0x75
#define I2C_INSTANCE i2c1

#define VOUT_REGISTER 0x04 